export default {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGOUT: 'LOGOUT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_CANCELLED: 'LOGIN_CANCELLED',
  SAVE_TOKEN: 'SAVE_TOKEN',
  DELETE_TOKEN: 'DELETE_TOKEN',
}